# Generated by Django 4.2.11 on 2024-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_fournisseur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
